import 'dart:convert';
import 'dart:async';
import 'dart:math' as math;

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:camera/camera.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_ai/firebase_ai.dart'
    show Content, FirebaseAI, GenerationConfig, InlineDataPart, TextPart;
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:geolocator/geolocator.dart' as geo;
import 'package:image_picker/image_picker.dart';
import 'package:image/image.dart' as img;
import 'package:latlong2/latlong.dart' hide Path;
import 'package:google_sign_in/google_sign_in.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';

import 'config/rosario_data.dart';
import 'core/web/browser_device.dart';
import 'core/web/video_frame_grabber.dart';
import 'firebase_options.dart';

part 'app/bfp_gis_app.dart';
part 'app/theme/app_colors.dart';
part 'core/constants/map_constants.dart';
part 'core/constants/security_constants.dart';
part 'core/firebase/firebase_services.dart';
part 'core/services/social_auth_service.dart';
part 'core/routing/user_role.dart';
part 'core/routing/role_helpers.dart';
part 'core/utils/auth_error_messages.dart';
part 'core/utils/field_parsers.dart';
part 'core/services/activity_log_service.dart';
part 'core/services/account_email_index_service.dart';
part 'core/services/emergency_call_service.dart';
part 'core/services/push_notification_service.dart';
part 'core/services/place_search_service.dart';
part 'core/services/presence_service.dart';
part 'core/models/dashboard_counts.dart';
part 'core/models/map_point.dart';
part 'core/models/incident_risk.dart';
part 'features/auth/role_gate.dart';
part 'features/auth/admin_web_only_scaffold.dart';
part 'features/auth/auth_scaffolds.dart';
part 'features/auth/login_screen.dart';
part 'features/auth/citizen_register_dialog.dart';
part 'features/auth/id_auto_scanner.dart';
part 'features/auth/forgot_password_dialog.dart';
part 'features/auth/legal_dialog.dart';
part 'features/auth/session_guard.dart';
part 'features/shared/shell.dart';
part 'features/shared/dashboard_counts_builder.dart';
part 'features/citizen/citizen_pages.dart';
part 'features/barangay_staff/barangay_staff_pages.dart';
part 'features/bfp/bfp_pages.dart';
part 'features/admin/admin_pages.dart';
part 'features/shared/common_pages.dart';
part 'features/shared/charts_and_map.dart';
part 'features/shared/ui_components.dart';
part 'features/shared/incident_model.dart';
