// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtrsnxhrVO5uEjNSWTH8StaMI9s0x_lIQ',
    appId: '1:886535672450:web:55999d42640e3ef3905a9b',
    messagingSenderId: '886535672450',
    projectId: 'gis-cross-platform',
    authDomain: 'gis-cross-platform.firebaseapp.com',
    storageBucket: 'gis-cross-platform.firebasestorage.app',
    measurementId: 'G-TPG1458FW4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBunz39FpCwU2EoZlpDo29k-LtYXekUt8k',
    appId: '1:886535672450:ios:caccd0918e57b881905a9b',
    messagingSenderId: '886535672450',
    projectId: 'gis-cross-platform',
    storageBucket: 'gis-cross-platform.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBunz39FpCwU2EoZlpDo29k-LtYXekUt8k',
    appId: '1:886535672450:ios:caccd0918e57b881905a9b',
    messagingSenderId: '886535672450',
    projectId: 'gis-cross-platform',
    storageBucket: 'gis-cross-platform.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-KbT79fF-9qBpCpakRSIsf8v-Wb2Ig0',
    appId: '1:886535672450:android:21565ff75a24a08c905a9b',
    messagingSenderId: '886535672450',
    projectId: 'gis-cross-platform',
    storageBucket: 'gis-cross-platform.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtrsnxhrVO5uEjNSWTH8StaMI9s0x_lIQ',
    appId: '1:886535672450:web:55999d42640e3ef3905a9b',
    messagingSenderId: '886535672450',
    projectId: 'gis-cross-platform',
    authDomain: 'gis-cross-platform.firebaseapp.com',
    storageBucket: 'gis-cross-platform.firebasestorage.app',
    measurementId: 'G-TPG1458FW4',
  );
}
